PMC_IGNORE_TAGS = {
	"table",
	"table-wrap",
	"disp-formula",
	"inline-formula",
	"ref-list",
	"bio",
	"ack",
	"graphic",
	"media",
	"tex-math",
	"mml:math",
	"object-id",
	"ext-link",
	"xref",
}

PMC_SPLIT_TAGS = {
	"table",
	"table-wrap",
	"title",
	"p",
	"sec",
	"break",
	"def-item",
	"list-item",
	"caption",
}

PMC_KEEP_TAGS = {
	"sup",
	"sub",
	"italic",
	"bold",
	"underline",
	"monospace",
	"sc",
	"overline",
	"strike",
}

PMC_ALLOWED_SUBSECTIONS = {
	"abbreviations",
	"additional information",
	"analysis",
	"author contributions",
	"authors' contributions",
	"authors’ contributions",
	"background",
	"case report",
	"competing interests",
	"conclusion",
	"conclusions",
	"conflict of interest",
	"conflicts of interest",
	"consent",
	"data analysis",
	"data collection",
	"discussion",
	"ethics statement",
	"funding",
	"introduction",
	"limitations",
	"material and methods",
	"materials",
	"materials and methods",
	"measures",
	"method",
	"methods",
	"participants",
	"patients and methods",
	"pre-publication history",
	"related literature",
	"results",
	"results and discussion",
	"statistical analyses",
	"statistical analysis",
	"statistical methods",
	"statistics",
	"study design",
	"summary",
	"supplementary data",
	"supplementary information",
	"supplementary material",
	"supporting information",
}
